### Post "Hello!"
POST http://localhost:8080
Content-Type: application/json

{
  "text": "Hello!"
}

### Post "Bonjour!"
POST http://localhost:8080
Content-Type: application/json

{
  "text": "Bonjour!"
}

### Post "Privet!"
POST http://localhost:8080
Content-Type: application/json

{
  "text": "Privet!"
}

### get all the messages
GET http://localhost:8080/

### delete all the messages
DELETE http://localhost:8080/

### delete message by id
DELETE http://localhost:8080/id/5e2f708e-fc0e-4189-a437-4bfbf6d6f7f0